services:
  postgres:
    container_name: postgres-oppostunities-api
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: openings_db
    ports:
      - 5432:5432